### ISSUE TITLE
__init__.py not included in PIP package or binary file

### ISSUE THREAD

**Issue by e2jk** [e2jk/billingflatfile#26]
```
C:\Users\[SNIP]\Documents\devel\billingflatfile\dist>billingflatfile.exe --help
Traceback (most recent call last):
  File "billingflatfile.py", line 418, in <module>
  File "billingflatfile.py", line 320, in init
  File "billingflatfile.py", line 151, in parse_args
  File "billingflatfile.py", line 18, in get_version
FileNotFoundError: [Errno 2] No such file or directory: '__init__.py'
[2712] Failed to execute script billingflatfile
```

**Comment by e2jk** [comment]
Solved in https://github.com/e2jk/billingflatfile/commit/ab4ffae8d71a59d5404500f55032dd5b8ae05fd4
